var newsArray;

function updateNewsArray() {
newsArray = [
    ["Welcome to Tuba's Tree, the game where you can go from 0 points to e22,895,400 points.",true,"a1"],
    ["Thank you for playing Tuba's Tree and taking the time to read this!",true,"a2"],
    ["Disabling the news ticker is not allowed",true,"a3"],
    ["'OMG it's just a Synergism clone' -literally everyone",true,"a4"],
    ["If AD has matter, why doesn't Tuba's Tree have anti-points?",true,"a5"],
    ["Cool Bug Fact: You know what you did",true,"a6"],
    ["'no' -randomtuba",true,"a7"],
    ["The tax man hasn't caught up to you yet...although the shard salesman did softcap your gains.",true,"a8"],
    ["'thonkeres' -TheMKeyHolder",true,"a9"],
    ["Vue can and will fuck up your code. Be careful",true,"a10"],
    ["Click the big cookie to get more cookies!",true,"a11"],
    ["'Reincarnating without shards is like wiping your ass without toilet paper' -Sun Tzu, Art of War", true, "a12"],
    ["https://www.youtube.com/watch?v=DLzxrzFCyOs",true,"a13"],
    ["Current Endgame: Limit of break_eternity.js",true,"a14"],
    ["You're going places.",true,"a15"],
    ["Tuba's Tree v1.0 - Coming Soon",true,"a16"],
    ["What if we pissed in the ball pit together? Unless...",true,"a17"],
    ["TMT needs more pride and accomplishment",true,"a18"],
    ["Tuba's Tree: Tuba's only game that gets updated",true,"a19"],
    ["This game isn't too short, you're just speedrunning it",true,"a20"],
    ["Thanks to the #modding-help channel for making this game come true. Without it, I would suck at coding. With it, I still suck at coding.",true,"a21"],
    ["Here's a fun challenge: Browse the code in layers.js and take a shot every time you see a ternary operator",true,"a22"],
    ["The news ticker is similar to Minecraft's splash text: It's there, it can't be disabled, and you ignore it after a while.",true,"a23"],
    ["'I fixed the bug and it's now back' -randomtuba",true,"a24"],
    ["Do Alt+F4 for 10x speed for 5 hours!",true,"a25"],
    ["Fun Fact: The news ticker code used in Tuba's Tree (news.js) is directly copy+pasted from Prestige Game, which means Tuba had to get rid of a lot of bad news ticker ideas. (especially the Homestuck references)",true,"a26"],
    ["Come to think of it, these messages really aren't that funny.",true,"a27"],
    ["Thanks to TMT, I don't have to add a bunch of libraries to begin. And I also don't have to implement saving!",true,"a28"],
    ["Balancing is hard",true,"a29"],
    ["Suggest news tickers in #tubas-tree on the TMT Reborn server!",true,"a30"],
    ["[insert text here]",true,"a31"],
    ["showNews();",true,"a32"],
    ["Fun Fact: SuperCesi once mispronounced my name as 'randomtuber'",true,"a33"],
    ["I miss the days when prestige had a currency called b. Those were the times...",true,"a34"],
    ["You know, the 5 hour joke has really gotten old",true,"a35"],
    ["sussy impostor from Amon Gus at 3am??? *NOT CLICKBAIT*",true,"a36"],
    ["timewall gaming",true,"a37"],
    ["You can't kill News Ticker Man, look at me go!",true,"a38"],
    ["bruh moment",true,"a39"],
    ["#MakeTidePodsEdibleAgain",true,"a40"],
    ["Don't you hate when the message doesn't finish its sente",true,"a41"],
    ["Important Message: Prestige points are not edible. Stop attempting to eat them.",true,"a42"],
    ["'It's not a fetish I swear'",true,"a43"],
    ["Whomst'd've'zh'bh'rh't'd've done this?!",true,"a44"],
    ["Good CSS? Good CSS is impossible.",true,"a45"],
    ["Here's a guide to the 3 different types of balancing! Jacorbian Balancing: Solid gameplay in earlygame and midgame, but too much strategy in lategame. Aarex Balancing: Solid gameplay in earlygame, but too many AAREX TIMEWALLS in midgame and lategame. Reinhardt Balancing: We don't talk about Reinhardt Balancing.", true, "a46"],
    ["While incremental games can be fun and even healthy in certain contexts, they can exacerbate video game addiction even more than other genres. If you feel like playing incremental games is taking priority over other things in your life, or manipulating your sleep schedule, it may be prudent to seek help.",true,"a47"],
    ["please stop comparing my game to synergism it's not a synergism clone pls i only copied the layer names they're watching please help stop it please get out of my head get out of my head get out of my head",true,"a48"],
    ["h",true,"a49"],
    [":ripaarex:",true,"a50"],
    ["Fun Fact: Reincarnation is the last prestige layer. You will not be able to become the Singularity.",true,"a51"],
    ["'shit game remove timewalls' -reda",true,"a52"],
    ["Don't quote me on this",true,"a53"],
    ["'I need triple exponential growth or else I'm not playing' -someone",true,"a54"],
    ["https://yahtzeemaster26.github.io/Algebraic-Progression/",true,"a55"],
    ["'Prestreestuck is a poorly balanced incremental because it's a homestuck fangame' -randomtuba",true,"a56"],
    ["Tuba's Tree??? More like Synergism!!! Am I right guys??? \xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0 ok now you're supposed to laugh",true,"a57"],
    ["Get the @tuba-tree role in the TMT Reborn server to get pinged every time Tuba's Tree gets a major update!",true,"a58"],
    ["Press F for nothing to happen. Seriously, try it.",true,"a59"],
    ["Press M to max all",true,"a60"],
    ["TUBA IS EMPTY",true,"a61"],
    ["'YESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS' - randomtuba",true,"a62"],
    [". . .",true,"a63"],
    ["'Need more layers!' -Aarex",true,"a64"],
    ["This news ticker is not what you anticipated",true,"a65"],
    ["Is this a Synergism reference?",true,"a66"],
    ["'smh my head' -Reinhardt",true,"a67"],
    ["Kaboom? Yes Rico, kaboom.",true,"a68"],
    ["Nice.",true,"a69"],
    ["Offline progress is in this game! If you have something better to do than play this game, then go offline for a bit and come back to receive some progress!",true,"a70"],
    ["Schrodinger's Prestige Layer - You don't know what content it has until you reset.",true,"a71"],
    ["Hmm yes, the points here are made out of points",true,"a72"],
    ["Fun Fact: layers.js has over 1000 lines of code!",true,"a73"],
    ["Did you just say that Antimatter Dimesions has better than Tuba's Tree? Are you seriously?!?!?! Tuba's Tree are much so better than Antimatter Dimesions. You be must taking drugs or something. go commit toaster bath",true,"a74"],
    ["wuantum when",true,"a75"],
    ["sowwy for kiwwing youw famiwwy, it's time to weave youw mowtal fwesh *stabs you cutely* OwO 5x",true,"a76"],
    ["Nerf quark energy pls",true,"a77"],
    ["No, I think that mechanic's too overpowered, it'll cause inflatio-hahaha spirits go BRRRRRRRRR-",true,"a78"],
    ["No, you shouldn't do that in a mechanic, that'll make the players quit playi-hahaha shard timewalls go BRRRRRRRRR-",true,"a79"],
    ["If you're in the transcension challenges era and don't know what to do: DO THE CHALLENGES IN ORDER. STOP ASKING ME THIS QUESTION.",true,"a80"],
    ["new layer coming 2023",true,"a81"],
    ["When life gives you lemons, you sacrifice it for the next lemon-related prestige layer.",true,"a82"],
    ["When is the next update, you ask? It'll be released in about 4.9999 hours!",true,"a83"],
    ["can u dont",true,"a84"],
    ["Breaking News: A person named 'randomtuba' was arrested due to being accused of stealing from an incremental game titled 'Synergism'.",true,"a85"],
    ["Sadistic could probably be completed without any row 4 ascension upgrades",true,"a86"],
    ["Shower Thoughts: Can glass bounce?",true,"a87"],
    ["You will arrive at your destination in: 5 1/2 cooked timewalls, medium rare, with a side of steak and mashed-up green beans",true,"a88"],
    ["Jokes? Half of these news tickers aren't even jokes.",true,"a89"],
    ["#news-ticker-suggestions when?",true,"a90"],
    ["Completing the game isn't really much of an Achievement",true,"a91"],
    ["too short 1/0",true,"a92"],
    ["Word of the day: poggers",true,"a93"],
    ["If I'm not mistaken, today is [insert date here]",true,"a94"], //If I'm not mistaken 1
    ["'When's the 5th prestige layer' -everyone at some point",true,"a95"],
    ["378-667-7036",true,"a96"],
    ["Haha 69 funni numb3r!!1!1",true,"a97"],
    ["#not-funny-didnt-laugh",true,"a98"],
    ["''Need more quotes!' -Hevipelle' -AD news ticker",true,"a99"],
    ["BREAKING NEWS: randomtuba has been kidnapped and is being forced to update the game",true,"a100"],
    ["Mythos? There is no mythos here.",true,"a101"],
    ["'We need at least 1000 news tickers before the players stop playing' -randomtuba",true,"a102"],
    [":thonk:",true,"a103"],
    ["Want a Sprite Cranberry?",true,"a104"],
    ["When the school shooting is unacceptable, but the chips are impeccable. Chips Ahoy is here for it.",true,"a105"],
    ["1,000,000 Zeroes tree when?",true,"a106"],
    ["Reincarnation Points will be the next currenc-wait what? It's gonna be called...'quarks'? Wow, people are so unoriginal nowadays.",true,"a107"],
    ["unfuckemup",true,"a108"],
    ["I'm not reviving Prestige Game. It's as good as dead.",true,"a109"],
    ["OMG PETER GRIFIN FROM GUYY FAMILY SAID THE P**** WORD!!1!1",true,"a110"],
    ["TubaStuck^2: Beyond Cringe",true,"a111"],
    ["Press B to buy accelerator boosts.",true,"a112"],
    ["Cool experiment: Type 'I'm actually 12' in a random channel on any Discord server and wait for your account to get terminated",true,"a113"],
    ["discord nitro is waste of money lol",true,"a114"],
    ["'Discord is not a good thing.' -Michael Stevens, also known as 'VSauce'",true,"a115"],
    ["Putting more exclamation marks at the end of your sentence doesn't make it have more emphasis, instead, it makes you look stupid",true,"a116"],
    ["The 3rd shard buyable unlocks at [REDACTED]. It costs NaNeNaN^NaNeNaN points.",true,"a117"],
    ["Tuba's Nitro subscription will end on September 11, 2021.",true,"a118"],
    ["Jadronize coming 2029",true,"a119"],
    ["In the beginning, there was nothingness. There was white space, and the only thing that existed was the news ticker. It looked really dumb. But then a rift appeared, and randomtuba emerged from the rift. He created some cool shit like Points, Prestige Points, Ascension Points, and Shards. He made buyables really powerful, so powerful that it crashed the fucking stock market. But randomtuba didn't care, he was too busy fucking up the game until he had to ask people in #modding-help about how he fucked up his own game. He also added some useless automation crap, whatever that means. Then randomtuba said he was done, and he created Google Chrome so ge could host the Glitch project on GitHub. He called it 'Tuba's Tree', an unoriginal and narcissistic title for a game that doesn't need to exist. So, is the game good? That's really funny, it's obviously a load of shit, 1/10",true,"a120"],
    ["If you want to see Tuba's terrible code, go to https://github.com/randomtuba/Tubas-Tree.",true,"a121"],
    ["Message from the future: It took 6 years for v1.0 to come out. Good luck waiting.",true,"a122"],
    ["Enter the E, we have cookies",true,"a123"],
    ["Fun Fact: The function that calls the news ticker code is called doodooWater(). In November 2020, Tuba thought this was very funny.",true,"a124"],
    ["This game is major garbo warbo",true,"a125"],
    ["Some of these news tickers were stolen from Prestige Game",true,"a126"],
    ["Reach eee1,000,000 points to unlock the next prestige layer!!! Don't worry, it's possible!!!",true,"a127"],
    ["Click to disassemble this news ticker for trace amounts of papercli-nah just kidding, this isn't mobile AD",true,"a128"],
    ["Tuba's Tree is excited to present a new mechanic: Lootboxes! Open them up for new prestige layers and more shard timewalls!",true,"a129"],
    ["Buy the new KITCHEN GUN today!",true,"a130"],
    ["This is the final news tickern't",true,"a131"],
    ["supercesi pls play my game",true,"a132"],
    ["mmm yummy timewalls",true,"a133"],
    ["<script>I hope this news ticker isn't an example of XSS",true,"a134"],
    ["b needs to be re-added in Tuba's game",true,"a135"],
    ["i like ya cut g",true,"a136"],
    ["Procrastination is fun! Fun until it hunts you down, at least...",true,"a137"],
    ["ha, comedy",true,"a138"],
    ["Are there any duplicate news tickers?",true,"a139"],
    ["Are there any duplicate news tickers?",true,"a140"],
    ["'smh' -smh",true,"a141"],
    ["9th dimesion coming out in 5 hours",true,"a142"],
    ["hey guys make sure to subscribe to the Tuba's Tree YouTube channel, now with only 4.20e69 subscribers!",true,"a143"],
    ["'let's ban randomtuba' -abraham lincoln",true,"a144"],
    ["mmm monkey",true,"a145"],
    ["What if pigs could actually fly? At least, that's what randomtuba's old custom status was.",true,"a146"],
    ["In an alternate universe, all the (softcapped) are replaced with (obscured), the scalings have no names, and {copyright strike by Jacorb's Games}",true,"a147"],
    ["'I'm 4 OoMs ahead of you' -capitalist mario, probably",true,"a148"],
    ["C is real 2401",true,"a149"],
    ["'pls don't ban me mod' -the banned guy",true,"a150"],
    ["How many ticks can a tick tick at?",true,"a151"],
    ["If C# is a programming language, what about Cb?",true,"a152"],
    ["Back to the drawing board. Or, I mean, let's get back to the point. *seinfeld music plays*",true,"a153"],
    ["break_your_sanity.js",true,"a154"],
    ["9th dimesion wehn???",true,"a155"],
    ["Esta oración está en español y no agrega nada a este juego.",true,"a156"],
    ["If I'm not mistaken, the current version number is v0.5.",true,"a157"], //If I'm not mistaken 3
    ["Anti-Cars 2 a huge hit",true,"a158"],
    ["Timewalls? Well, this game isn't Ordinal Markup, that's what.",true,"a159"],
    ["go touch grass",true,"a160"],
    ["Kowalski, Transcend.",true,"a161"],
    ["You won't have to break your M key, this game isn't AD",true,"a162"],
    ["Hey look ma, I'm on the news!",true,"a163"],
    ["Mrs. Obama, I've done it, I've stopped racism.",true,"a164"],
    ["It do be like that",true,"a165"],
    ["Every 18000 seconds in Africa, 5 hours pass. Together we can stop this.",true,"a166"],
    ["#randomtubaisoverparty",true,"a167"],
    ["Shrek is love, shrek is life.",true,"a168"],
    ["Eventually randomtuba's gonna make an FE000000 reference. Eventually...",true,"a169"],
    ["Let's get riiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiight into the news!",true,"a170"],
    ["/give randomtuba discord:owner_permissions 1",true,"a171"],
    ["Does randomtuba just pick quotes to put in the game?",true,"a172"],
    ["lasted",true,"a173"],
    ["Supercesi thumbnails be like - Episode 42069: OVERENTHUIASTIC TITLE WITH A LOT OF EXCLAMATION MARKS AT THE END!!!!!!!!",true,"a174"],
    ["ew light theme",true,"a175"],
    ["Just keep waiting, you'll unlock new content eventually",true,"a176"],
    ["1/10, need more ants",true,"a177"],
    ["You can stop now",true,"a178"],
    ["One day, a boy found a mysterious bag in his backward. It labeled: 'Duplicator Food'. There was also a small metallic cube that was called: 'Antimatter Galactic Brand Replicanti'. There was also a small blue spiked sphere that was called: 'Universe Expander Brand Duplicators'. The boy took the replicanti and the duplicator and tried to put them together, but they repelled each other. But then, the boy took the duplicator food within the bag and put it near the duplicator. And then, just like that, the duplicators started replicating. Then the replicanti replicated. The two self-replicating objects attacked each other. The boy heard whispers of 'AD is better!' and 'UE is better!' and then, the replicanti whispered, 'UE got abandoned just like Despacit's other mods!', and the duplicators whispered, 'AD's Reality Update will never come out!', and then the two currencies disappeared. They were never found ever since, and the bag is empty.",true,"a179"],
    ["Therapist: Sadistic III isn't real, it can't hurt you\xa0\xa0\xa0\xa0Sadistic Challenge III:",true,"a180"],
    ["Show me your war face! AAAAAA! Show me your timewall face! AAAAAAAAAAAAAAAA!!!",true,"a181"],
    ["Tuba's Tree = Thanos Tower, they have the same abbreviation",true,"a182"],
    ["Now, this is a story all about how my save got flipped-turned upside down...",true,"a183"],
    ["Check out randomtuba's YouTube channel, it has absolutely no content at all",true,"a184"],
    ["'no memes in #general' -Discord moderator stereotype",true,"a185"],
    ["You've just been news tickered, send a screenshot of this news ticker to get un-news tickered",true,"a186"],
    ["It's difficult to come up with actually funny news tickers",true,"a187"],
    ["MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-sorry that wasn't my keyboard, that was actually my microwave. Ooh, my pizza's ready!",true,"a188"],
    ["<i>If this sentence appears italic, then that's intentional</i>",true,"a189"],
    ["No more meta-news, I promise. (ok I don't actually promise that)",true,"a190"],
    ["I didn't steal any news tickers from NG+++",true,"a191"],
    ["Just wait six hours and your package will arrive",true,"a192"],
    ["Anti-Jake from StateFarm says that he is not on your side.",true,"a193"],
    ["Recipe for anti-cereal: it's just the same as the recipe for cereal, but pour the milk before the anti-bowl is even on the table",true,"a194"],
    ["LOOK AT THE MOON-oh wait, this isn't Local58",true,"a195"],
    ["John, I want a divorce.",true,"a196"],
    ["Transcension Challenge 11 when?",true,"a197"],
    ["sussy! sussy! sussy! sussy! sussy! sussy! sussy! sussy! sussy! sussy! sussy! sussy! sussy! sussy! sussy! sussy! sussy! sussy! sussy! sussy!",true,"a198"],
    ["LOOK AWAY",true,"a199"],
    ["Level 1 crook, Level e22,895,400 boss, that's how Tuba's Tree works.",true,"a200"],
    ["Uh oh. We have a problem. The Onionpocalypse has started! Onions are raining from the sky, there are onionadoes and onionamis, people's heads are being turned into onions...this may be my final entry. My hand may have become an onion. AAAAAHHH!",true,"a201"],
    ["The 'N' in 5 hours stands for Not Funny.",true,"a202"],
    ["So you thought the 5 hours joke was stupid. Well, I'll give you something stupid-er. *ahem* One day, it was a beautiful day. The birds were singing, the flowers were blooming...and then Aarex said to everyone, 'The update will instead take 5.0000000000000000000001 hours instead of exactly 5.' Everyone screamed. People were terrified. 'AAAAAAAAAAHHHH!' someone yelled. 'WAAAAAAHHH!' a baby cried. 'This is a dream, right?' said an old man. The city fell into anarchy and soon, the evil matter of people's souls took over them, and everyone died except for Aarex. The end.",true,"a203"],
    ["Aw snickerdoodle, the news got filtered again. Fudgecrackers!",true,"a204"],
    ["madden 08 best game",true,"a205"],
    ["Anti-Aarex can do side projects earlier.",true,"a206"],
    ["Anti-Virtual Boy amazing console",true,"a207"],
    ["There was an AI made of dust, Whose poetry gained it man's trust, If is follows ought, It'll do what they thought, In the end we all do what we must.",true,"a208"],
    ["I hope you don't refresh. This news is very interesting. It's a very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very long news ticker. Here. Let me start. Well, I can't go far. If only there was some sort of character limit then I wouldn't be able to go very far. Welp, here we g",true,"a209"],
    ["ti daer t'nac uoy ,esrever ni si egassem sihT",true,"a210"],
    ["Portal 3 announced to release on December 32nd",true,"a211"],
    ["Dohn't yoo haet whenn ppl yooz incurrecct speling?",true,"a212"],
    ["Anti-fortnite flopped",true,"a213"],
    ["Anti-Avengers: Endgame is the worst movie to ever exist. It has been given a -1% on Rotten Tomatoes.",true,"a214"],
    ["1.79e308 NO SCOPED",true,"a215"],
    ["Don't you hate when you suggest a bunch of news tickers and they never get added? Oh wait...this isn't relatable to anyone",true,"a216"],
    ["˙˙˙sᴉɥʇ ʇnoqɐ ʇɥƃᴉɹ lǝǝɟ ʇ,usǝop ƃuᴉɥʇǝɯos 'ʎǝH",true,"a217"],
    ["No microtransactions whatsoever! What a surprise!",true,"a218"],
    ["In the beginning, there were 4 nations: wait this copypasta is not funny.",true,"a219"],
    ["How am I meant to get pregananant.?",true,"a220"],
    ["WW91IHJlYWxseSB0b29rIHRoZSB0aW1lIHRvIGRlY29kZSB0aGlzIGludG8gbm9ybWFsIHRleHQ/",true,"a221"],
    ["Legend has it that Tuba is still taking a break from Tuba's Tree.",true,"a222"],
    ["If you ever get to 2^^6 points, you cheated",true,"a223"],
    ["Just Monika.",true,"a224"],
    ["Big Rip snapped its fingers. 'EP, I don't feel so good,' TT said. 'I don't want to go, I don't want to go...' 'Hey! Get ahold of yourself!' EP said, gripping TT. 'I'm sorry,' TT said, and it disintegrated away.",true,"a225"],
    ["Gods have such a short lifespan. They only live up to 10^308 years.",true,"a226"],
    ["Congratulations @idiot, you are now level 9! -MEE6",true,"a227"],
    ["randombathtub",true,"a228"],
    ["Don't talk to me or my son ever again.",true,"a229"],
    ["Breaking News: This news message is very handsome",true,"a230"],
    ["Is this a jojo reference?",true,"a231"],
    ["Another buyable bites the dust",true,"a232"],
    ["I dare you to click this news ticker.",true,"a233"],
    ["Don't you hate when people put a period instead of a question mark in their sentence.",true,"a234"],
    ["BREAKING NEWS: This news ticker is mispeled",true,"a235"],
    ["Hlp. Th ky btwn 'w' and 'r' is missing.",true,"a236"],
    ["Do you know why there is no period in this news ticker? It's because there is no period key on our keyboard",true,"a237"],
    ["BREAKING NEWS: News ticker suggestions channel has been lasted for the 89th time, no more news tickers!",true,"a238"],
    ["We decided to kill ourselves so we could Ghostify in real life...",true,"a239"],
    ["Aarex thinks everything is a competition. EVERYTHING.",true,"a240"],
    ["It's funny when you explain the joke. You see, this news ticker is funny because it is explaining its own joke, and it says 'It's funny when you explain the joke.'. This is meant to taken in a sarcastic and ironic manner.",true,"a241"],
    ["'LESS GO DABABY' -randomtuba",true,"a242"],
    ["Ow, that hurt! Stop clicking me!",true,"a243"],
    ["Click this news ticker for absolutely nothing",true,"a244"],
    ["There is no such thing as a 5th prestige layer. Proof: The Reality Update isn't out yet.",true,"a245"],
    ["@randomtuba#8432",true,"a246"],
    ["In these 'In these trying times' times, we're working hard to find a vaccine for COVID-19.",true,"a247"],
    ["guys help this isn't a news ticker, I'm stuck in randomtuba's basement forced to make news tickers, I've wrote 248 of them, I haven't had food in 5 days, please call 911 before they-HAHAHAHA FUNNY RANDOMTUBA QUOTE JOKE HAHAHAHAHAAHAHAHAHAHAHAHAHA-",true,"a248"],
    ["Vorona's news ticker barely works, so I had to make my news ticker through other means. screw this im touching virus",true,"a249"],
    ["ah yes, stomehuck",true,"a250"],
    ["Welcome to the truest of travels.",true,"a251"],
    ["So no one told me bugs were gonna be this wayyy. *clap clap clap clap* The code's a joke, game broke, a fix is on the wayyy...",true,"a252"],
    ["The letters stand for Park, Reverse, Neutral, Drive, and LOW!",true,"a253"],
    ["ngl those numbers lookin kinda t h i c c",true,"a254"],
    ["Bee Movie 2 coming in 6 hours",true,"a255"],
    ["https://dan-simon.github.io/misc/fe000000",true,"a256"],
    ["The AD server has too many blob emojis. Change my mind",true,"a257"],
    ["Resistance is futile.",true,"a258"],
    ["randomtuba should stop drinking 10 gallons of valve oil",true,"a259"],
    ["New news company has become rivals with us. The company name is 'Universal Paperclips, Inc.' They also make paperclips that gain a lot of Trust.",true,"a260"],
    ["'we have more news tickers than content, epic' -Cosmic47",true,"a261"],
    ["put this in the news ticker put this in the news ticker put this in the news ticker put this in the news ticker put this in the news ticker put this in the news ticker put this in the news ticker put this in the news ticker put this in the news ticker put this in the news ticker put this in the news ticker put this in the news ticker put this in the news ticker",true,"a262"],
    ["Please hold. *hold music*",true,"a263"],
    ["Bet you can't count to a hundred thousand right now",true,"a264"],
    [":kappa:",true,"a265"],
    ["Tuba's TTree speedrun when?",true,"a266"],
    ["Hippity hoppity, that buyable is now my property",true,"a267"],
    ["Hippity hoppity, that challenge is now my property",true,"a268"],
    ["Ka-chow!",true,"a269"],
    ["guys should I steal some AD news tickers",true,"a270"],
    ["The reason why there aren't many long news tickers is because randomtuba didn't really decide to make a bunch of long news tickers...until now.",true,"a271"],
    ["Pardon me, coming through!",true,"a272"],
    ["Going horizontal is fun! Weeeeeeeeeeeeee!",true,"a273"],
    ["I was planning to make 1,000,000 of these before the update, but I ran out of ideas.",true,"a274"],
    ["NOTICE: This news ticker message is a placeholder. We are currently coming up with new news tickers. Please wait until the next one.",true,"a275"],
    ["Several people are typing...",true,"a276"],
    ["Thanks, Obama.",true,"a277"],
    ["oh wait wrong discord server",true,"a278"],
    ["Ah yes, my quarks are inflating like crazy ever since I bought that ascension upgrade! AND THEN ALONG CAME ZEUS-",true,"a279"],
    ["never gonna give you up never gonna let you down never gonna run around and desert you *rickroll music plays* never gonna make you cry never gonna say goodbye never gonna tell a lie and hurt you *more rickroll music plays*",true,"a280"],
    ["This ticker is sponsored by Skillshare",true,"a281"],
    ["'Um, Tuba...the vault of bad news ticker ideas are filling up again! We need to fix this quick or else the whole building will fill up with news ticker messages!' -Tuba's Tree dev, 30 seconds before his demise",true,"a282"],
    ["Fun fact: Masks are actually gay",true,"a283"],
    ["'someone to die? hehewoowowowowow' - abraham lincoln",true,"a284"],
    ["'fucking eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee' -unp©gged™",true,"a285"],
    ["hyperinflation when?",true,"a286"],
    ["new phone who dis",true,"a287"],
    ["Everyone asks who made the ticker, but not how they made the tickers",true,"a288"],
    ["Breaking News: A group of people are starting a riot at Tuba's house because he didn't add a 5th prestige layer.",true,"a289"],
    ["Procrastination has gotta be the reason why the game hasn't been updated",true,"a290"],
    ["next patch in 5 minutes",true,"a291"],
    ["",true,"a292"],
    ["Slowmode is enabled.",true,"a293"],
    ["'So that's y' -jan Misali",true,"a294"],
    ["I'm sorry Dave, but I'm afraid I can't do that.",true,"a295"],
    ["'Gonna make you die, SAY GOODBYE' -Rick Astley",true,"a296"],
    ["AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAREX TIMEWALLS",true,"a297"],
    ["tuba's place is a Discord server I should get rid of",true,"a298"],
    ["This statement is false.",true,"a299"],
    ["In the code, this news ticker is the 300th news ticker!",true,"a300"],
    ["Thanks to prestige points for making the game possible.",true,"a301"],
    ["special thanks to spaghetti code",true,"a302"],
    ["Oh no, hyperinflation! Oh, they were using the console.",true,"a303"],
    ["Quark dimesions coming in v0.6",true,"a304"],
    ["Hehehe I'm going to advertise in #general and- oh wait I'm banned.",true,"a305"],
    ["Enter 'Cancer' for a secret- WHAT?!?! There are no secret themes??? Oh wait, this is TMT, implementing custom themes is hard.",true,"a306"],
    ["don't go into the console plz",true,"a307"],
    ["is this a reference to nothing? yeah, it is.",true,"a308"],
    ["v1ee10.0.0 coming out in 5 centuries",true,"a309"],
    ["Experiment: Use <script> in a news ticker. Result: Tuba's Tree is safe from cross-site scripting.",true,"a310"],
    ["Fun fact: there is more than 2 tickers in the game!",true,"a311"],
    ["Fun Fact: We ran out of ideas for news tickers very quickly.",true,"a312"],
    ["Base64 encoding is not a good way of encrypting things because there's a website to decode it. But no one cares, not even me!",true,"a313"],
    ["Click this news ticker for +0.0000000000000000000000001 points",true,"a314"],
    ["Imagine the chaos that would occur if dark theme didn't exist.",true,"a315"],
    ["The 5th layer is not real...or is it?",true,"a316"],
    ["In 3 decades Aarex timewalls won't exist. Incrementals will be completable in under 3 minutes.",true,"a317"],
    ["'Dark Theme > Light Theme' -randomtuba",true,"a318"],
    ["google.com would like to know your location",true,"a319"],
    ["a1000 does not exist",true,"a320"],
    ["Press CTRL+W for 5x shards production!",true,"a321"],
    ["'How did I get 0.015172485164829616 b from 5 b' -randomtuba",true,"a322"],
    ['iPhone 69 coming 2021',true,"a323"],
    ["'goodbye word' -DEMEMZEA",true,"a324"],
    ["'bruh' -hurb",true,"a325"],
    ["Hi, this is not a joke ticker, but it is just to show how tickers are made. The code of the news ticker was made by an australian, and this is his video: https://youtu.be/oHg5SJYRHA0",true,"a326"],
    ["'I am going to force Jacorb to update TPT:R, I need more procrastination' -randomtuba",true,"a327"],
    ["'I'm just trying to get my name on the tickers' -Froasans",true,"a328"],
    ["Help, I've fallen, and I can't get up!",true,"a329"],
    ["Hey man, you don't think you can put my idea in your news ticker without paying me, do you?",true,"a330"],
    ["I dare you to get 'Nice^2' on your first run",true,"a331"],
    ["testerest",true,"a332"],
    ["I'm gonna say the n-word...NEXTUPDATEINFIVEHOURS",true,"a333"],
    ["Point buyables when?",true,"a334"],
    ["Hey shitass, wanna see me speedrun Tuba's Tree?",true,"a335"],
    ['"""""""""""":kekw:" -randomtuba" -unpogged" -The Nefarious DDT" - unsoftcapped" -The Nefarious DDT" -unpogged" -unsoftcapped" -unpogged" - faroshkas" -The Nefarious DDT" -unsoftcapped" -unpogged" - randomtuba"',true,"a336"],
    ["Fun Fact: ",true,"a337"],
    ["Tick tock, hurry up, the news is ticking...",true,"a338"],
    ["Fun Fact: randomtuba has made a lot of Discord games, only 3 of them have been completed.",true,"a339"],
    ["Tuba's Tree 2 is never coming out.",true,"a340"],
    ["'you leaked the test link >:(' -every developer with a game that has test links",true,"a341"],
    ["lol, 300 + 42",true,"a342"],
    ["stop();",true,"a343"],
    ["when are we reaching ee69.420 :weary:",true,"a344"],
    ["I can't keep going like this. We need to stop.",true,"a345"],
    ["You know, it's very difficult trying to come up with actually good news ticker. The things is, when I made this news ticker, I had code with 400 news tickers. I had to replace a lot of them because most of them were either reference a different incremental's mechanics, or were just not funny. I might ask people in the #tubas-tree channel on the TMT: Reborn server to come up with news tickers for me because I just don't have good ideas. So, if you have any ideas for news tickers, feel free to give them to me. I would appreciate it.",true,"a346"],
    ["FINALLY! The update is released! Just going to publish it and- 1ee308 more bugs?!?!?!",true,"a347"],
    ["Wait, why isn't Ascension the 4th prestige layer? I thought Transcension was next!",true,"a348"],
    ["The next TPT mod Tuba will make will be called 'The Geometree'. Wait a minute, it's too late, the name's already been taken.",true,"a349"],
    ["Error: cannot load layer_5.exe",true,"a350"],
    ["Error: Error error error",true,"a351"],
    ["BREAKING NEWS: Florida man blows up his own home with firework launchers",true,"a352"],
    ["Pokemon #151 has ascended into the clouds. This is the cause for Aurora Borealis in the sky.",true,"a353"],
    ["The news ticker no longer works...\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0 News Ticker Is Being Fixed\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0 Maybe it is almost fixed\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0 How is this still being fixed\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0 *Loud Machine Noises* \xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0 Almost There\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0 It turns out all you need to do is reload\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0 Or maybe you dont?",true,"a354"],
    ["These get worse and worse every day I write.",true,"a355"],
    ["'Never gonna let you up, never gonna give you down...wait, are those the lyrics...what's my name again?' -Rick Astley with Stage 4 dementia",true,"a356"],
    ["// no comment.",true,"a357"],
    ["Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",true,"a358"],
    ["Seeing your numbers go up fills you with determination. GAME SAVED",true,"a359"],
    ["Bro you just posted cringe, you are going to lose subscriber",true,"a360"],
    ["Alright, let's check the gages for the tickers. Hmmm...0.000039% real news, 46.26% jokes, and 101.89% trash. That can't be right. Maybe we have to try harder.",true,"a361"],
    ["You are entering: The E",true,"a362"],
    ["Tuba's Tree est. April 13 2009",true,"a363"],
    ["??????????????",true,"a364"],
    ["Input: new Decimal(10^^9e15). Output: [REDACTED]",true,"a365"],
    ["Tuba's Tree: Will it blend?!",true,"a366"],
    ["Are you stuck? Well, don't worry! A guide for Tuba's Tree is being worked on.",true,"a367"],
    ["randomtuba wants to know your location",true,"a368"],
    ["'are you looking at THIS?!' -some guy pointing at a green screen",true,"a369"],
    ["hlep supercesi reahc 100 bazliilion subscirbresrc!!!1!1 aaa /b2",true,"a370"],
    ["are you putting something in here? (no)",true,"a371"],
    ["bottom textn't",true,"a372"]
    ["'Alright...let's set this thing up here...there! It's here! I think we are live on the news.' 'Wait, we are?' 'Yes, we are!' 'Alright, I'm a bit shy on camera...but ok!' 'Hello everyone! It is I, Tick Bickerson, back with another episode of...Tick Bickerson News! I hope you all enjoy. Anyway, let's begin, shall we? First things first, Florida man attempts to use his computer as a campfire by running Minecraft RTX. Interesting news! Next up is a live report from Tarawashki Mayamoto.' 'Hello, it is I, Tarawashki Mayamoto, here live in Chicago. There has been a new 'Incremental Game Convention', which has all of your favorite incremental games! Let's take a trip inside.' *opens door* 'Wow, interesting! It sure looks like there are a lot of games here. Antimatter Dimensions, Omega Layers, Ordinal Markup, Realm Grinder...wow there sure is everything! What is your opinion, Calvin? Gimme some real talk like I do on this show!' 'Well, Tick...I'm not really focused on that. Ummm, the Antimatter Cannons are pointed directly towards us.' 'I don't see it. Did you take your pills?? Get back to your job!' 'Uh, Bickerson, I'm not lying-' 'I don't care, Calvin! Stop asking questions and do your damn job!' 'But sir-' 'SILENCE!' 'We should wrap things up sir-' 'Fine, fine! We'll be back to you after this commercial break. I have some brains to kick back into people's heads. Anyway, THIS IS TICK BICKERSON, SIGNING OFF!' 'OH GOD THE CANNONS-' *static* Technical Difficulties - Please Stand By",true,"a373"],
    ["Look at the time, now add 1 to the time, than subtract it, what do you have left... maybe the answer is in your heart.",true,"a374"],
    ["I'm tired.",true,"a375"],
    ["Welcome to mildly infuriating",true,"a376"],
    ["Listen to me, I can't help anymore... I'm stuck in the 9th dimesion... everyone is dying... INCLUDING YOU!",true,"a377"],
    ["You invented a quantum storage box just to contain your immense wealth of points.",true,"a378"],
    ["'Time is an interesting concept, you can make it faster and slower... but sometimes, by doing this you make it disappear forever, and we don't want to remake your timeline!' -Eternity, the High God of Time",true,"a379"],
    ["Finally. You have gotten beyond the AAREX TIMEWALLS and have reached Row 8. You now have to go through more AAREX TIMEWALLS and more grinding. Where are those mastery bricks anyway...fuck.",true,"a380"],
    ["I can't take it anymore. This needs to end.",true,"a381"]
    ["Did you ever think about how your alarm clock is the theme of your TV show?",true,"a382"],
    ["Remember kids, to make sure that you win the heads contest, use fire and lightning.",true,"a383"],
    [".. ..-. / -.-- --- ..- / . ...- . .-. / .-.. . .- .-. -. / .-- .... .- - / - .... .. ... / -- . .- -. ... --..-- / -.-- --- ..- / .-- .. .-.. .-.. / -... . / .--. .-. --- -- --- - . -.. / - --- / .- / - . ... - . .-. / .. -. / - .... .. ... / --. .- -- . .----. ... / -.. .. ... -.-. --- .-. -.. / ... . .-. ...- . .-. --..-- / -... ..- - / --- -. .-.. -.-- / .. ..-. / -.-- --- ..- / .- .-. . / ..-. .. .-. ... - .-.-.-",true,"a384"],
    ["BREAKING NEWS: Tuba's Tree was a commercial success! Oh wait, wrong game.",true,"a385"],
    ["We're putting Tuba's Tree on Steam in 2030! Good luck trying to wait for that long.",true,"a386"],
    ["Enter the F when?",true,"a387"],
    ["Where does Spongebob live? He lives in a pineapple under the sea. What, did you except a cheesy pun or an obscure reference? Maybe even an inside joke? You're playing the wrong game, buddy.",true,"a388"],
    ["YIAY #722: In just 4 words, describe incremental games. Answer 1: 'absolute waste of time'.",true,"a389"]
    ["Here's a hint, maybe morse code might be useful someday???",true,"a390"],
    ["'Too many long news tickers, you've clogged up my inbox yet again' -literally no one",true,"a391"],
    ["The Prestige Game Tree",true,"a392"],
    ["'do it that way we can put memes in general' -upvoid",true,"a393"],
    ["'hey guys can we-' -not make chains",true,"a394"],
    ['"if another intercom is being created thats kinda cool, gives me another excuse to shut down this stupid fucking idiot bot sooner" -Yhvr',true,"a395"],
    ["Error: Maximum quote amount reached. Turn off the console immediately.",true,"a396"],
    ["yesfwuefuiweuiwegueghiuwreughweigweioioewoigweorhg,,,,,,,,",true,"a397"],
    ["Cats are better than dogs.",true,"a398"],
    ["'oWo' -OwO",true,"a399"],
    ["If you see this news ticker, I just want to let you know that I wish you have a great day. If you're experiencing something rough, just remember that this too shall pass. Good luck, my friend.",true,"a400"]
];} 
var s;
var scrollTimeouts = []; 
var nextMsgIndex;
function doodooWater() {
  s = document.getElementById("news");
  scrollNextMessage();
}

function scrollNextMessage() {
  updateNewsArray();
  //select a message at random

  try {
    do {nextMsgIndex = Math.floor(Math.random() * newsArray.length)} while (!eval(newsArray[nextMsgIndex][1]))
  } catch(e) {
      console.error("Newsarray doesn't work at idx " + nextMsgIndex)
  }

  scrollTimeouts.forEach(function(v) {clearTimeout(v);});
  scrollTimeouts = [];
    
  //set the text
  s.textContent = newsArray[nextMsgIndex][0];
  //get the parent width so we can start the message beyond it
  let parentWidth = s.parentElement.clientWidth;

  //set the transition to blank so the move happens immediately
  s.style.transition = '';
  //move div_text to the right, beyond the edge of the div_container
  s.style.transform = 'translateX('+parentWidth+'px)';

  //we need to use a setTimeout here to allow the browser time to move the div_text before we start the scrolling
  scrollTimeouts.push(setTimeout( function() {
    //distance to travel is s.parentElement.clientWidth + s.clientWidth + parent padding
    //we want to travel at rate pixels per second so we need to travel for (distance / rate) seconds
    let dist = s.parentElement.clientWidth + s.clientWidth + 20; //20 is div_container padding
    let rate = 140; //change this value to change the scroll speed
    let transformDuration = dist / rate;


    //set the transition duration
    s.style.transition = 'transform '+transformDuration+'s linear';
    let textWidth = s.clientWidth;
    //we need to move it to -(width+parent padding) before it won't be visible
    s.style.transform = 'translateX(-'+(textWidth+5)+'px)';
    //automatically start the next message scrolling after this one finishes
    //you could add more time to this timeout if you wanted to have some time between messages
    scrollTimeouts.push(setTimeout(scrollNextMessage, Math.ceil(transformDuration * 1000)));
  }, 100));
}
